### ISSUE TITLE
consolidate project board across spec and sdk and other smi repos

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#100]
https://help.github.com/en/github/managing-your-work-on-github/linking-a-repository-to-a-project-board

@lachie83 -- looks like I don't have sufficient permissions to edit the project board to link other repos to it. Would you mind helping us out here?

**Comment by bridgetkromhout** [comment]
I have consolidated all project boards to https://github.com/servicemeshinterface/smi-spec/projects.
