### ISSUE TITLE
Need a discussion on validating user intent in SMI policy 

### ISSUE THREAD

**Issue by asridharan** [servicemeshinterface/smi-spec#105]
In an  ongoing PR #67  there has been consensus in re-defining the notion of a service within the context of an SMI policy to allow SMI spec to support multiple Kubernetes clusters as well as to support services running outside a Kubernetes cluster such as on VMs.

The proposal led to a debate, revolving around the notion of authorization within the SMI policy, namely, how does the service mesh implementation determine whether the access that is specified between two services within the policy is valid, and given its validity how does the service mesh enforce this access?

Creating this issue to track the discussion.

**Comment by asridharan** [comment]
Here is a proposal on this topic:
https://docs.google.com/document/d/1tiEDUgx9wjdBBi-AjBMr6I94XnzX57rezPvamZ0djBE/edit?usp=sharing

**Comment by grampelberg** [comment]
Would you mind either doing a PR or opening up comment access on that?

**Comment by asridharan** [comment]
@grampelberg just opened it up for comments. Could you give it a try? 

Thanks !!
