### ISSUE TITLE
Refresh README

### ISSUE THREAD

**Issue by lachie83** [servicemeshinterface/smi-spec#106]
Include:
- Who we serve (application integrators, eg. Kiali and Flagger)
- Application integration
- Tooling integration
- LCD service mesh definition
- List integrations and implementations
- Version information
- For the customer and benefits (make it easy, not locked to provider)

Other suggestions welcome.

**Comment by bridgetkromhout** [comment]
https://github.com/deislabs/smi-spec/pull/57 also will need a link.
