### ISSUE TITLE
ValidatingAdmissionWebhook

### ISSUE THREAD

**Issue by grampelberg** [servicemeshinterface/smi-spec#11]
At launch, not all meshes will have implementations for all the APIs. It doesn't feel like the APIs will be fully implemented either. Should the specification explicitly call out providing a `ValidatingAdmissionWebhook` that messages users they've configured a feature that is not supported by the underlying implementation?

**Comment by ritazh** [comment]
@grampelberg is this the same issue you were thinking about?

cc @lachie83

**Comment by ritazh** [comment]
and this seems to be related: https://github.com/deislabs/smi-spec/issues/59

**Comment by grampelberg** [comment]
Nope, but this is a good one too. I just put #73 together for the schema validation.
