### ISSUE TITLE
Provide overview of ecosystem

### ISSUE THREAD

**Issue by tomkerkhove** [servicemeshinterface/smi-spec#111]
Being new to SMI it's hard to get an understanding of who supports SMI in their service meshes/tooling.

Are there plans to highlight them on http://smi-spec.io/?

**Comment by grampelberg** [comment]
Yup! See #106. We'd love a PR if you're up for it =)

**Comment by tomkerkhove** [comment]
Happy to help if I knew who supports it 😅

Is the CNCF donation deck up to date?

Do I add them to the Readme or SMI-spec.io?

**Comment by grampelberg** [comment]
While both would be awesome, I don't actually know how to update the site. @michelleN any ideas?

Support AFAIK today is:

- Linkerd
- Istio
- Consul Connect
- Maesh

**Comment by tomkerkhove** [comment]
Docs are on https://github.com/deislabs/smi-spec.io - I'll have a look at both!

**Comment by bridgetkromhout** [comment]
Both PRs are merged! Since the scope of this issue could grow without bound, I'll resolve this now and we can continue to make iterative improvements. Thanks, @tomkerkhove!

**Comment by tomkerkhove** [comment]
My pleasure!
