### ISSUE TITLE
Update license to Apache v2

### ISSUE THREAD

**Issue by lachie83** [servicemeshinterface/smi-spec#120]
As part of the donation to CNCF the license needs to be updated to Apache v2.

We will also have to update the code of conduct

**Comment by bridgetkromhout** [comment]
This was completed in https://github.com/servicemeshinterface/smi-spec/pull/122 as far as I can tell; please re-open if further work is required.

**Comment by bridgetkromhout** [comment]
Ah! Perhaps we need to revisit this for all the repos in this org? I'll add a checklist here.

**Comment by lachie83** [comment]
smi-adapter-istio updates - https://github.com/servicemeshinterface/smi-adapter-istio/pull/82

**Comment by bridgetkromhout** [comment]
Updates completed.
