### ISSUE TITLE
[Proposal] Adopt Kubernetes Ingress v2 in SMI

### ISSUE THREAD

**Issue by stefanprodan** [servicemeshinterface/smi-spec#123]
In my option the service mesh interface should include ingress and egress specifications of how north/south traffic flows into/out of the mesh.

I propose for SMI to adopt [Kubernetes Ingress v2](https://github.com/kubernetes-sigs/service-apis) as the service mesh interface ingress specification. Adoption can happen as an endorsement of the Kubernetes spec or by merging the two specs under SMI org. I'm in favour of merging since both SMI and Ingress v2 specs overlap in areas like traffic shifting, HTTP routes, match conditions, access roles, etc. For example, instead of having two specifications for TrafficSplit, it would be beneficial to unify the two.

**Comment by danehans** [comment]
A big thank you to @grampelberg for joining the Service APIs weekly meeting and shedding light on SMI. I think we agree that overlapping APIs is :-( 

We just need to figure out the details of aligning our efforts across the two projects. I think it's beneficial if @grampelberg or someone from the SMI community can stay connected to the Service APIs project.

**Comment by ryandawsonuk** [comment]
I see there's an SMI [nginx traffic splitting example](https://docs.nginx.com/nginx-service-mesh/tutorials/trafficsplit-deployments/) at but it doesn't use the nginx ingress controller. There's also a [non-SMI nginx traffic splitting example](https://github.com/nginxinc/kubernetes-ingress/tree/master/examples-of-custom-resources/traffic-splitting) that does use the ingress controller but Ingress resources aren't involved.

I was wondering if there's eventually a desire to handle traffic splitting in an Ingress way. Perhaps others reading this issue wonder the same. There's an issue on the [k8s github on that which has closed](https://github.com/kubernetes/kubernetes/issues/25485) and there have been suggestions that k8s [might move in a different direction](https://www.cncf.io/blog/2020/10/29/kubernetes-1-19-the-future-of-traffic-ingress-and-routing/).

@stefanprodan perhaps you could explain where Ingress v2 fits into this?
