### ISSUE TITLE
Add specification for previous released versions

### ISSUE THREAD

**Issue by adleong** [servicemeshinterface/smi-spec#131]
This repo only contains a description of the most recent version of each API.  It would be helpful to have descriptions of previous versions as well.

One way to do this would be to have a directory for each version, e.g. `v1alpha1`, `v1alpha2`, etc.

It would also be useful to have a directory for the next working version of the spec, called `unreleased`, `working`, or something similar.  This would serve as an area to develop the next version of the spec and would be renamed to a new version when it is ready to be released.  In this way, released versions of the spec would be immutable.

**Comment by adleong** [comment]
I hope the intention is clear here.  Please let me know if I can clarify anything.  I'm also happy to put together a pull request demonstrating what I mean if that would be helpful.

**Comment by bridgetkromhout** [comment]
Looks like @stefanprodan is also thinking about versioning in https://github.com/servicemeshinterface/smi-spec/issues/88.

**Comment by adleong** [comment]
I think what is described here is compatible with the ideas in #88.  In particular, that there would be a top-level directory for each version (v1alpha1, v1alpha2, etc.) and each directory would contain the released specifications for all of the SMI APIs.  I think this helps make it more intuitive that all the APIs of a given version are compatible with each other.  @stefanprodan does that sound correct to you?

**Comment by stefanprodan** [comment]
@adleong Yes I see two options here, we either go with the dir per version option or with a branch per version. I'm inclined towards branches.

**Comment by adleong** [comment]
I have a preference for directories because I feel like they're more discoverable and easier to work with than branches.  But yeah, I think either of those options would work well.

**Comment by shashankram** [comment]
If multiple versions of SMI can co-exist (ie. supporting backward compatibility), documentation for those versions would need to exist together. I would suggest to also cut release branches when SMI announces a new version of the spec.

**Comment by michelleN** [comment]
I like the idea of going for directories especially for discoverability especially since things are still changing in the short term. In the long term, release branches make sense since users probably only want to see major versions and not necessarily alpha/beta changes per spec category.

**Comment by michelleN** [comment]
I think we need to start talking about the version of the spec as a whole regardless of versions of the individual APIs and if multiple APIs at a given release then those should be described in directories like @adleong suggested.

**Comment by michelleN** [comment]
prior art:
https://github.com/cnabio/cnab-spec#branchtag-structure
https://github.com/cnabio/community/blob/master/governance.md#development-process

https://github.com/theupdateframework/specification#the-update-framework-specification

OCI has different repos for runtime-spec, image spec, distribution spec
https://github.com/opencontainers/runtime-spec
https://github.com/opencontainers/image-spec
https://github.com/opencontainers/distribution-spec
