### ISSUE TITLE
Add swagger definitions for APIs

### ISSUE THREAD

**Issue by adleong** [servicemeshinterface/smi-spec#132]
It would be great to have some kind of formal specification for the APIs in this repo; swagger, for example.

**Comment by stefanprodan** [comment]
A formal specification for the APIs (except for metrics) is here: https://github.com/servicemeshinterface/smi-sdk-go/tree/master/crds I've added OpenAPI schema to all CRDs.

**Comment by stefanprodan** [comment]
We could move the CRDs in this repo or move the metrics OpenAPI definition in the SDK, it's going be to very confusing if we don't use a single repo for all definitions.

**Comment by tomkerkhove** [comment]
I think that sounds fair to have the definition in this repo.
