### ISSUE TITLE
Clarification on Traffic Split's spec.backend.service

### ISSUE THREAD

**Issue by shashankram** [servicemeshinterface/smi-spec#145]
Quoting from https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-split.md:
`Implementations will weight outgoing traffic between the services referenced by spec.backends. Each backend is a Kubernetes service that potentially has a different selector and type. Weights must be whole numbers.`

The word `potentially` is not clear to me. It seems to me the backend services should have different selectors, otherwise there is no way to assign weights if multiple deployments with different versions of the service have the same label selector for the app.
Conversely, if multiple deployments use the same service but version their deployments and container images instead of their services and use the same label selector for the service, the Traffic Split spec does not provide a means to achieve splitting traffic by weights because `backend.service` is just a service name.

**Comment by grampelberg** [comment]
@shashankram the point is that the spec doesn't dictate selectors on the services. A user could do whatever they want. It is pretty common for folks to have an apex and leaf service with identical selectors (usually the same name in fact) with a separate leaf to send traffic to slowly.

**Comment by shashankram** [comment]
> @shashankram the point is that the spec doesn't dictate selectors on the services. A user could do whatever they want. It is pretty common for folks to have an apex and leaf service with identical selectors (usually the same name in fact) with a separate leaf to send traffic to slowly.

@grampelberg If the backends services (leaf services) in the Split belong to the same selector, what's the expectation?

**Comment by grampelberg** [comment]
@shashankram if all the leaves in the split belong to the same selector, then the traffic will be distributed to everything in that single selector. This would be the case for a single leaf or many.
