### ISSUE TITLE
Clarification on the definition of the various metrics supported by SMI Metrics

### ISSUE THREAD

**Issue by snehachhabria** [servicemeshinterface/smi-spec#153]
According to the SMI metrics spec, the various metrics supported are : response latency (99,90 and 50 percentile), success count and failure count. 

Is there a definition on each of these metrics and what data they are suppose to represent exactly ? An explanation of these would be helpful for extraction of the relevant data from the service mesh implementing it.

**Comment by grampelberg** [comment]
@snehachhabria would you mind explaining your question more?

**Comment by snehachhabria** [comment]
I was looking into implementing the spec via SMI metrics API and noticed that the implementation for Linkerd and Istio had their own yaml files that queried for different stats. I understand that this would be different for every service mesh, I'd like a definition of the metric to understand which stat is the best representation of that . For instance the definition of response latency so that I can get the relevant stat and build my query based on that stat

**Comment by grampelberg** [comment]
https://landing.google.com/sre/sre-book/chapters/monitoring-distributed-systems/#xref_monitoring_golden-signals

**Comment by grampelberg** [comment]
@snehachhabria please ask more questions if that doesn't answer it for you! Happy to help =)

**Comment by snehachhabria** [comment]
@grampelberg I think I am good for now with the definitions you shared, will definitely reach out if I have more doubts
