### ISSUE TITLE
Correlation between two canary active deployments

### ISSUE THREAD

**Issue by jeusdi** [servicemeshinterface/smi-spec#163]
Imagine the next situation:

  * two services:
    * `users service`
    * `audit service`

`user service` talks with `audit service` in order to journal auditories.

So, both services are running a canary deployment strategy at the same time, one for `users service` and one another for `audit service`.

When both canary deployment strategies are active means that two versions of each service are running: a `canary` and a `primary`.

So, when `users service` receives a request could be handled by `canary` or `primary`.

**ISSUE**: Once a request is handled by `users service canary`, derived requests to `audit service` should be handled by `audit service canary`.

So, how could I keep this correlation:
  * `users canary` -> `audit canary`
  * `users primary` -> `audit primary`

I hope I've explained so well.

**Comment by grampelberg** [comment]
The most sustainable way to do this would be with an ingress controller which adds a header based on where it should be going. Propagate the headers and clients down the chain can make decisions about where to send it. Take a look at the A/B test example - https://github.com/servicemeshinterface/smi-spec/blob/master/traffic-split.md.

Adding a `source` selector to TrafficSplit seems like an interesting idea and would allow for matching based on where the traffic is originating.
