### ISSUE TITLE
Tag 0.4.0 release of specification

### ISSUE THREAD

**Issue by lachie83** [servicemeshinterface/smi-spec#174]
We plan to release the SDK - https://github.com/servicemeshinterface/smi-sdk-go/issues/81

**Comment by lachie83** [comment]
dep - https://github.com/servicemeshinterface/smi-sdk-go/issues/81

**Comment by michelleN** [comment]
We're currently at the working draft for v0.4.0 of the spec which includes
- TrafficSplit v1alpha3
- TrafficTarget v1alpha1
- TrafficSpecs v1alpha2
- TrafficMetrics v1alpha1

We have not yet defined a release process for the spec. I think we should open a PR that bumps the version in SPEC.md to v0.4.0 and points to the API versions listed above. Then, cut a release branch tagged v0.4.0. We should also update the readme to point to the SPEC.md file in that branch.

**Comment by michelleN** [comment]
If we go this route, we also probably need to create a spec-v0.4.0.md file or spec-latest-stable.md or something along those lines so we can still have a working-draft file for the spec.

**Comment by michelleN** [comment]
Release plan:

1. Create a PR with following changes:
- Create a file called spec-v0.4.0.md
- Rename SPEC.md to spec-working-draft.md and update version in the file to v0.5.0-WD
- Update README.md to point to spec-v.0.4.0.md and add a table in README [like the one in the CloudEvents spec](https://github.com/cloudevents/spec#cloudevents-documents) which points to the latest release of each doc as well the current working draft.
3. Merge PR.
4. Create a tag v0.4.0
5. Cut a GitHub release v0.4.0
