### ISSUE TITLE
rename TrafficTarget to TrafficAccess

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#177]
**Describe the proposal**
rename TrafficTarget to TrafficAccess

**Scope**
- [ ] New specification
- [x] Traffic Access Control
- [ ] Traffic Specs
- [ ] Traffic Metrics
- [ ] Traffic Split

**Possible use cases**
This might be easier to understand and more intuitive. Would love to know the origin of the name TrafficTarget if someone has context.

**Comment by stefanprodan** [comment]
I think TrafficAccess better defines what the API does 👍

**Comment by patricekrakow** [comment]
Indeed, when I started to look at SMI, I have been confused by this suffix "Target". The API is called "Traffic Access Control" in the documentation, the API Group is `access.smi-spec.io`, and the kind is _TrafficTarget_, and not (yet?) _TrafficAccess_.

**Comment by patricekrakow** [comment]
@michelleN I can make the PR for this one if it's OK with you.

**Comment by michelleN** [comment]
That would be great. Thank you @patricekrakow

**Comment by patricekrakow** [comment]
Before I start with the PR, I would like to summarize the possible options I see.

### AS-IS

| **APIs**               |**group**| **Kind(s)**                        |
| ---------------------- | ------- | ---------------------------------- |
| Traffic Specs          | specs   | HTTPRouteGroup, TCPRoute           |
| Traffic Access Control | access  | TrafficTarget                      |
| Traffic Split          | split   | TrafficSplit                       |
| Traffic Metrics        | metrics | TrafficMetrics, TrafficMetricsList |

### TO-BE Options

The changes will be shown in _italic_

#### Option 1

| **APIs**               |**group**| **Kind(s)**                        |
| ---------------------- | ------- | ---------------------------------- |
| Traffic Specs          | specs   | HTTPRouteGroup, TCPRoute           |
| Traffic Access Control | access  | _TrafficAccess_                    |
| Traffic Split          | split   | TrafficSplit                       |
| Traffic Metrics        | metrics | TrafficMetrics, TrafficMetricsList |

#### Option 2

| **APIs**         |**group**| **Kind(s)**                        |
| -----------------| ------- | ---------------------------------- |
| Traffic Specs    | specs   | HTTPRouteGroup, TCPRoute           |
| _Traffic Access_ | access  | _TrafficAccess_                    |
| Traffic Split    | split   | TrafficSplit                       |
| Traffic Metrics  | metrics | TrafficMetrics, TrafficMetricsList |

#### Option 3

| **APIs**               | **group**         | **Kind(s)**                        |
| ---------------------- | ----------------- | ---------------------------------- |
| Traffic Specs          | specs             | HTTPRouteGroup, TCPRoute           |
| Traffic Access Control | _access-control_  | _TrafficAccessControl_             |
| Traffic Split          | split             | TrafficSplit                       |
| Traffic Metrics        | metrics           | TrafficMetrics, TrafficMetricsList |

#### Option 4

| **APIs**               |**group**| **Kind(s)**                        |
| ---------------------- | ------- | ---------------------------------- |
| Traffic Specs          | specs   | HTTPRouteGroup, TCPRoute           |
| Traffic Access Control | access  | _TrafficAccessControl_             |
| Traffic Split          | split   | TrafficSplit                       |
| Traffic Metrics        | metrics | TrafficMetrics, TrafficMetricsList |

Let me know if you have a preference for any of these options, or even another permutation I would have missed...

**Comment by michelleN** [comment]
Hey @patricekrakow - option 2 looks the most clear to me. Would you still be able to work on this issue?


cc/ @johnsonshi
