### ISSUE TITLE
Change "master" branch to "main"

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#180]
Echoing the sentiments here: https://github.com/kubernetes/website/issues/21749#issue-638401894

@lachie83 used this guide in another repo to perform this task: https://github.com/chancancode/branch-rename/#simple-migration

**Comment by bridgetkromhout** [comment]
It appears that this issue was missed when https://github.com/servicemeshinterface/smi-spec/issues/200 was opened; closing this one as there is more detail there.
