### ISSUE TITLE
SMI Metrics and OpenTelemetry

### ISSUE THREAD

**Issue by mhausenblas** [servicemeshinterface/smi-spec#199]
We discussed [SMI Metrics](https://docs.google.com/document/d/1NEOu0wbcfQmk1xS9Q61dIQLyOKXajQl-WaMWf0LIsT8/edit) recently and the question came up how we can align with [OpenTelemetry](https://opentelemetry.io/) in this respect.

**Comment by justinfoote** [comment]
Do you have a desire to use OpenTelemetry to instrument SMI implementations? If so, we could absolutely talk about how to make that possible.

I've been working on the OpenTelemetry specification, especially on semantic conventions for metrics. We have conventions defined already for [system metrics](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/system-metrics.md) and metrics related to [HTTP operations](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/semantic_conventions/http-metrics.md) and we're working on conventions related to [database](https://github.com/open-telemetry/opentelemetry-specification/pull/1076), [messaging](https://github.com/open-telemetry/opentelemetry-specification/pull/1077), [rpc](https://github.com/open-telemetry/opentelemetry-specification/pull/1162), [FAAS](https://github.com/open-telemetry/opentelemetry-specification/pull/1052), and [generic operations](https://github.com/open-telemetry/opentelemetry-specification/pull/1142). 

We could absolutely define some semantic conventions for SMI metrics as well. 

It would be worthwhile to discuss your requirements.  What shape will the metrics be? What units will you need? Will our labeling system be sufficient for your needs, etc...

**Comment by mhausenblas** [comment]
Thanks a lot @justinfoote and as I said on Gitter I'm more than welcome to be the liaison for this.

**Comment by tomkerkhove** [comment]
I think the ideal scenario here is where there is an SMI receiver that is available on https://github.com/open-telemetry/opentelemetry-collector-contrib so that we can easily bring SMI-compliant metrics in OpenTelemetry Collector.

I already have the first use-case which is https://github.com/kedacore/http-add-on/issues/354 where we want to standardize on OpenTelemetry's collector to use as a single-source of truth for traffic metrics.

**Comment by tomkerkhove** [comment]
Any thoughts on this idea to leverage an SMI receiver?
