### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by mhausenblas** [servicemeshinterface/smi-spec#200]
For obvious reasons, let's get the branch rename done.

**Comment by leecalcote** [comment]
I stuttered conscientiously when speaking of this today.

**Comment by bridgetkromhout** [comment]
Looks like it's pretty straightforward in https://github.com/github/renaming - we'd do it for this repo in https://github.com/servicemeshinterface/smi-spec/settings/branches

Any objections, speak up, and I'll mention that we'll be doing this, at the next meeting.

**Comment by bridgetkromhout** [comment]
Made the change for the associated website repo in https://github.com/servicemeshinterface/smi-spec.io/

**Comment by bridgetkromhout** [comment]
Updated all the servicemeshinterface org repos from `master` to `main`.
