### ISSUE TITLE
[Governance] Maintainer role: Definition of "active" 

### ISSUE THREAD

**Issue by leecalcote** [servicemeshinterface/smi-spec#203]
**Describe the proposal**
We're in need of a refinement of the measurements by which "active" maintainership is qualified.

**Scope**
- [X] All
- [ ] New specification
- [ ] Traffic Access Control
- [ ] Traffic Specs
- [ ] Traffic Metrics
- [ ] Traffic Split

**Comment by bridgetkromhout** [comment]
Closing due to project archival: https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/)
