### ISSUE TITLE
No warning if incorrect yaml is applied for Traffic Split 

### ISSUE THREAD

**Issue by mudit-01** [servicemeshinterface/smi-spec#235]
**Describe the proposal**

For traffic split, if weights are distributed in an improper way like all weights don't sum up to 100 or all weights sum > 100. We don't get an error message that yaml is incorrect.
**Scope**
- [ ] New specification
- [ ] Traffic Access Control
- [ ] Traffic Specs
- [ ] Traffic Metrics
- [X] Traffic Split

**Possible use cases**

apply the yaml with irregular weights like 1000, -200 etc. the yaml will be applied successfully without error. This should throw an error message.

**Comment by jbyers19** [comment]
Hi, @mudit-01. This was discussed on the SMI community call today and the consensus was that this proposal is outside the scope of this spec. Validation beyond that enforced by the OpenAPI schema in the [TrafficSplit CRD](https://github.com/servicemeshinterface/smi-sdk-go/blob/a143f8bc96eccdf5fc8a66d0c1622591104c77e0/crds/split.yaml#L112) is left to those implmenting this spec.

> if weights are distributed in an improper way like all weights don't sum up to 100 or all weights sum > 100

The weights are not percentages, so there should be no issue if the weights do not add up to 100.
