### ISSUE TITLE
Trafficsplit based on sourcelabel? 

### ISSUE THREAD

**Issue by hawk-liu** [servicemeshinterface/smi-spec#239]
we are testing linkerd+trafficsplit on our app, which based on springcloud.
but we want serviceA-canary->serviceB-canary->serviceC-canary, NOT serviceA-canary->serviceB-pro->serviceC-canary.
The doc only show trafficsplit based on http header or weight, is there any way to split traffic by sourcelabel like isito？

**Comment by bridgetkromhout** [comment]
@keithmattix points out this is referencing https://istio.io/latest/docs/reference/config/networking/virtual-service/#HTTPMatchRequest

**Comment by bridgetkromhout** [comment]
Similar topic: https://github.com/servicemeshinterface/smi-spec/issues/242
