### ISSUE TITLE
CRD installation

### ISSUE THREAD

**Issue by ylallemant** [servicemeshinterface/smi-spec#240]
I may be missing something, but where on earth do I get the CRD yamls from in order to install them on my cluster ?

some ecosystem project do set them up when you use they CLI but if you go for an other approach like the GitOps one from Traefik for example, the `manifest.yaml` does not provide the SMI CRDs...

https://doc.traefik.io/traefik-enterprise/installing/kubernetes/gitops/

Where do I get those ?

**Comment by nicholasjackson** [comment]
You can find the CRDs here: https://github.com/servicemeshinterface/smi-sdk-go/tree/main/crds, these are released along with the main specification.

If you are using the new controller-sdk the build process also creates CRDs: https://github.com/servicemeshinterface/smi-controller-sdk/tree/main/helm/smi-controller/templates

Please feel free to re-open if this does not resolve things for you
