### ISSUE TITLE
support queryParams in TrafficSpec

### ISSUE THREAD

**Issue by ryan4yin** [servicemeshinterface/smi-spec#242]
**Describe the proposal**

support queryParams params in TrafficSpec.

**Scope**
- [ ] New specification
- [ ] Traffic Access Control
- [x] Traffic Specs
- [ ] Traffic Metrics
- [ ] Traffic Split

**Possible use cases**

for traffic split, A/B Test service to service.

**Comment by bridgetkromhout** [comment]
Will consider at upcoming community call.
