### ISSUE TITLE
State of SMI Spec

### ISSUE THREAD

**Issue by guettli** [servicemeshinterface/smi-spec#253]
**Describe the proposal**

There were no changes since several month

Reading the announcement of [Gamma](https://smi-spec.io/blog/announcing-smi-gateway-api-gamma/), I am unsure
about the state of the SMI spec.

Please update the README so that new users understand the current state of SMI.

Thank you.

**Comment by tomkerkhove** [comment]
This was a bit explained in https://smi-spec.io/blog/announcing-smi-gateway-api-gamma/

**Comment by guettli** [comment]
Nevertheless it would be nice to get an official "state of the SMI project".

**Comment by tao12345666333** [comment]
I am not sure how SMI will develop after OSM is archived. 

https://openservicemesh.io/blog/osm-project-update/

**Comment by guettli** [comment]
I guess in the long run everybody will use Cilium. Then there is no need for a spec, because there is a single implementation. Just like Linux killed other Unixes.

**Comment by bridgetkromhout** [comment]
Thanks for reaching out. We have edited the README to indicate that the project is archived:
 https://www.cncf.io/blog/2023/10/03/cncf-archives-the-service-mesh-interface-smi-project/
