### ISSUE TITLE
Mocked impl playground

### ISSUE THREAD

**Issue by jshaughn** [servicemeshinterface/smi-spec#52]
The SMI backend is variable depending on the provider (istio, linkerd).   A mocked backend would be valuable for playing with and providing feedback on the proposed API.  With this we wouldn't need an actual mesh deployed, nor a fully implemented SMI impl for a specific provider.  Potential consumers of the API (and provider devs, I think) as SMI impls are coming on line.

For me personally, I'd like to see the Traffic Metrics ASAP.

This would likely also relieve pressure on providing full API specs via swagger or something like that.

**Comment by christian-posta** [comment]
Sounds interesting. So basically an API that hooks into Kubernetes apiservice.apiregistration.k8s.io and just returns a pre-defined TrafficMetrics list?

**Comment by grampelberg** [comment]
@christian-posta that's my thinking, makes it easy to write implementations on top when you've got metrics already there!

**Comment by jshaughn** [comment]
That right, guys.  I'm looking at this from a Kiali perspective, as a potential consumer of telemetry provided by SMI API.
