### ISSUE TITLE
Conformance Test Tool

### ISSUE THREAD

**Issue by leecalcote** [servicemeshinterface/smi-spec#70]
Like other specifications, SMI needs a set of conformance tests, conformance utility and dashboard.

Meshery used as the underlying technology for conformance tests with these goals and acknowledgments:
- A public, third-party compatibility matrix identifying the SMI features that are supported per service mesh.
- Definition of what behavior is expected and conforms to spec. vs not. Partial conformance could be defined by a minimum requirement. It may be that partial conformance allows for / encourages extensibility.
- Difference between conformance and full implementation given that some meshes may conscientiously never fully implement functions.

Meshery is soon to be used in the release process of each of the major service mesh projects for performance testing and as such can perform SMI validation testing at the same time.

[Design spec](https://docs.google.com/document/d/1HL8Sk7NSLLj-9PRqoHYVIGyU6fZxUQFotrxbmfFtjwc/edit#)

**Comment by lachie83** [comment]
Lets aim to have conformance requirements defined for the TrafficSplit API by KubeCon EU

**Comment by Dhiraj240** [comment]
@leecalcote I have forked this project and building it on my ubuntu now. I will be applying to Community Bridge.
May I know what all I need to do to work on this project. Also, may I know your slack or any other communication channel to discuss further.

**Comment by vaniisgh** [comment]
Hey!
 I noticed that the SMI Conformance Testing tool had been accepted under the Google Summer of Code this year, will a different issue be available for the community bridge mentees, or is the selection process already over for SMI?
I would like to apply for the same.
thanks & regards.
vani

**Comment by championshuttler** [comment]
Hey @leecalcote! I am willing to get mentored for this issue for the Community Bridge program. Can you please help me in getting started with it?

Thanks

**Comment by Dhiraj240** [comment]
@leecalcote Yes also I was not selected for CNCF unfortunately.
@championshuttler Is selected for CNCF and working for fluentd.
I will work on please check your email.

**Comment by CIPHERTron** [comment]
Heyy @leecalcote I wanted to contribute to this issue since my skill set matches with the required skills. Could you help me get started? Thank you!

**Comment by atharmohammad** [comment]
@leecalcote I would like to work on this as part of the LFX program. I have required skills of Golang and Reactjs and am interested in working on this and learning more things on the way , i have started looking into issue and any help and guidance is appreciated
