### ISSUE TITLE
Language inconsistency in traffic metrics

### ISSUE THREAD

**Issue by SirNexus** [servicemeshinterface/smi-spec#78]
Talking about [here](https://github.com/deislabs/smi-spec/blame/master/traffic-metrics.md#L126)

The language here is inconsistent with the rest of the README. A direction is described as the flow of traffic from resource to edge resource. However, the `to` keyword here was being used to described flow from all resources *to* the target resource.

Is this intended, or an oversight?

I propose: 

"Finally, `resource` can be as general or specific as desired. For example, with
a `direction` of `to` and an empty `resource`, the metrics are observed *at*
the `foo-775b9cbd88-ntxsl` pod and represent all traffic *to* other resources."

**Comment by grampelberg** [comment]
Hmmm, how about:

> Finally, `resource` can be as general or specific as desired. For example, with a `direction` of `to` and an empty `resource`, the metrics are for all the traffic *received* by the `foo-775b9cbd88-ntxsl` pod.

**Comment by SirNexus** [comment]
I like the "*to*" phrasing, because it emphasizes the intent of using the `to` keyword in the edge. But I understand that "other resources" is a big vague. 

However, if we change the wording to "received", perhaps don't italicize?  I think the reason *to* is italicized is to emphasize that the keyword `to` in the example represents traffic *to* a particular resource.

**Comment by grampelberg** [comment]
Yeah, I was finding that reusing `to` the confusing bit for me. The gist is that if `edge` doesn't actually point to anything, it is always the traffic being received by `resource`.

**Comment by SirNexus** [comment]
I am alright with your suggestion. Would you like me to open a PR? Do you still think the italics are warranted?

**Comment by grampelberg** [comment]
A PR would be awesome! I think you're right, the italics aren't required.
