### ISSUE TITLE
rate limiting and circuit breaking in SMI

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#80]
During the calls, multiple people have mentioned interest in seeing how we can define rate limiting and circuit breaking in the spec part of Traffic Split or in another object referenced by `TrafficSplit`. @grampelberg brought up the point that we need to define circuit breaking because there are multiple definitions as a first step. That's something I can take on. Does anyone have any additional thoughts on how they want to see these two things defined in SMI?

**Comment by grampelberg** [comment]
Wouldn't rate limiting be part of `TrafficTarget`?

**Comment by michelleN** [comment]
Yes! When we're trying to rate limit traffic to particular service or `destination`, it makes sense to specify that information as part of `TrafficTarget` because `TrafficTarget` allows us to define a set of rules around what traffic can be routed to the `destination`. Good catch. Thanks.
