### ISSUE TITLE
clarify versioning of APIs

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#88]
Having version in the header might be confusing. @bridgetkromhout brought this up as well.

- Let's add a description of how versioning works in the README
- Let's add that as a note/section under the header on the actual spec that describes the versions.

**Comment by stefanprodan** [comment]
As discussed in the last meeting, I propose to consolidate all API resources under the same version. With the current versioning we must provide users and implementers with a support matrix: e.g. TrafficSplit/v1alpha3 is compatible with HTTPRoutes/v1alpha2 but not with HTTPRoutes/v1alpha1.

**Comment by leecalcote** [comment]
This effort is about a compatibility matrix between smi-go-sdk and the specs, not about compatibility of conformance testing as described in #70, correct?

**Comment by stefanprodan** [comment]
> This effort is about a compatibility matrix between smi-go-sdk and the specs, not about compatibility of conformance testing as described in #70, correct?

Yes that's correct.

**Comment by michelleN** [comment]
I agree. I think this comment describes the same thing you're saying but let me know if it isnt: https://github.com/servicemeshinterface/smi-spec/issues/131#issuecomment-621293746
