### ISSUE TITLE
need a definition for weight

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#89]

**Comment by grampelberg** [comment]
There's a tradeoff discussion on it already - https://github.com/deislabs/smi-spec/blob/master/traffic-split.md#tradeoffs

Should that be higher or moved somewhere else? It seems that folks aren't getting to the tradeoff section at all.

**Comment by bridgetkromhout** [comment]
@michelleN Do you think this is covered by the link @grampelberg provided? If not, what do you think would be a good place for further details? Thanks.

**Comment by michelleN** [comment]
Weight is mentioned but there is no definition. I still think we need a definition for what we mean by weight when referencing it in the Traffic Split
