### ISSUE TITLE
HPA scaling on metrics

### ISSUE THREAD

**Issue by grampelberg** [servicemeshinterface/smi-spec#96]
It is valuable to scale workloads on metrics other than cpu/memory. To do this today, you must use the custom metrics API and the prometheus adapter. With the SMI metrics API it should be possible to get HPA working with that API. This project should integrate HPA and SMI metrics to allow for scaling on rps as well as latency.

**Comment by tomkerkhove** [comment]
This is very interesting - My name is Tom Kerkhove and working on Kubernetes Event-driven Autoscaling (KEDA).

We are looking to build upon the SMI spec with KEDA to provide exactly this: https://github.com/kedacore/keda/issues/538

Would you be up for collaborating on this or rather provide this yourself?

Happy to setup a call if you are interested.

/cc @jeffhollan @anirudhgarg

**Comment by grampelberg** [comment]
That'd be fantastic!
