### ISSUE TITLE
Transfer priorities from agenda to project board

### ISSUE THREAD

**Issue by michelleN** [servicemeshinterface/smi-spec#99]
https://docs.google.com/document/d/1NTBaJf6LhUBlF8_lfvBBt_MbyPvT-6CZNg6Ckpm_yCo/edit#heading=h.wpaq1r94m39s

**Comment by bridgetkromhout** [comment]
Moving notes to here so as to remove them from meeting agenda:

 Priorities

1. smi-sdk release and stability
   a. Potential issue with fake package (daniel)
      - TCP informer will not sync at all - repo at https://github.com/deislabs/smi-sdk-go/issues/33
1. Ecosystem tooling
    a. Flagger etc
    b. Kiali (need two or three things) - Lachie to follow up
    c. Tilt (canary deploy demos)
    d. Meshery (performance benchmarking)
    e. Gatekeeper validation of specifications
    f. Services on Windows (init container)
       - Need SMI based CNI integration
1. Update docs
1. Conformance/benchmarking
1. Progress milestones - Versioning [issue](https://github.com/deislabs/smi-spec/issues/68)
    a. Michelle suggests focusing on metrics for moving to beta
    b. TrafficSplit - maybe?? (rate limiting and circuit breaking)
